extends RefCounted

const Settings := preload("res://Settings.gd")
## Язык интерфейса. Один словарь на всю игру.
##
## Английский нужен не «когда-нибудь»: издатель, который не читает по-русски,
## просто не сможет оценить игру и остановится на стартовом экране. Текста тут
## немного — экраны, правила, десяток строк подсказок, — а без него срез не
## показать никому за пределами двух стран.
##
## Ключ — короткая латинская строка. Не сам русский текст: иначе любая правка
## формулировки молча ломает перевод.

const RU := {
	"title": "ТОЧКИ УЖАСА",
	"sub": "хоррор от первого лица  ·  играй в наушниках",
	"intro1": "Ты просыпаешься в полной темноте.",
	"intro2": "ОБЕРНИСЬ — на столе позади лежит палочка. Без неё нет света.",
	"intro3": "Найди семь полотен, соедини точки — и доберись до выхода.",
	"k_move": "идти",
	"k_look": "камера,  SHIFT — быстрее",
	"k_dash": "рывок,  а в захвате — вырываться",
	"k_flash": "вспышка палочки",
	"k_read": "книжка на столе, а на полотне — бросить его",
	"k_journal": "дневник записок",
	"k_thread": "нить: куда идти дальше",
	"k_turn": "развернуться кругом",
	"k_pause": "пауза",
	"k_restart": "начать заново",
	"k_mouse": "мышь  или  ← →",
	"music": "МУЗЫКА",
	"sounds": "ЗВУКИ",
	"controls": "УПРАВЛЕНИЕ",
	"bind_hint": "жми клавишу  •  ESC — отмена",
	"bind_reset": "ВЕРНУТЬ ЗАВОДСКИЕ",
	"bind_back": "НАЗАД",
	"bind_pad": "геймпад: левый стик — идти, правый — камера, A — рывок,\nX — вспышка, Y — взять, LB — быстрее, RB — развернуться,\nSTART — пауза, SELECT — дневник, крестовина вверх — нить",
	"b_forward": "вперёд",
	"b_back": "назад",
	"b_left": "влево",
	"b_right": "вправо",
	"b_run": "быстрее",
	"b_sprint": "рывок / вырываться",
	"b_quick_turn": "развернуться",
	"b_flash": "вспышка",
	"b_read": "взять / бросить",
	"b_journal": "дневник",
	"b_thread": "нить",
	"k_space": "ПРОБЕЛ",
	"r1": "Соединяй точки по порядку цветов, лента внизу полотна.",
	"r2": "Одинаковых цветов несколько — смотри на номерки у точек.",
	"r3": "Каждая соединённая точка съедает две секунды таймера.",
	"r4": "Каждая ошибка и каждая поимка делают лабиринт хуже.",
	"r5": "Пока рисуешь, ОН НЕ СТОИТ. Дойдёт — сорвёт холст и заберёт тебя.",
	"r6": "Услышал, что гул полотна стих, — он рядом. Бросай и беги.",
	"r7": "Услышал, как за спиной трещит камень — ОБЕРНИСЬ.",
	"r8": "На что смотришь, то не хватает.",
	"r9": "Три поимки подряд — и всё сначала.",
	"wake": "ПРОСНУТЬСЯ",
	"quit": "ВЫЙТИ",
	"credits": "БЛАГОДАРНОСТИ",
	"volume": "ГРОМКОСТЬ",
	"paused": "ПАУЗА",
	"resume": "ПРОДОЛЖИТЬ",
	"restart": "НАЧАТЬ ЗАНОВО",
	"wipe": "СТЕРЕТЬ ДНЕВНИК",
	"wipe_sure": "ТОЧНО СТЕРЕТЬ?",
	"wipe_done": "ДНЕВНИК ПУСТ",
	"quit_game": "ВЫЙТИ ИЗ ИГРЫ",
	"esc_back": "ESC — вернуться",
	"back": "НАЗАД",
	"cred_intro": "Звуки взяты с opengameart.org. Ниже — авторы и лицензии.",
	"cred_cc0": "CC0 — общественное достояние, указывать автора не обязано.",
	"cred_by": "BY — требует указания автора. Он выше.",
	"cred_rest1": "Всё остальное — шаги монстра, щупальца, гул полотна, капли,",
	"cred_rest2": "хлопки пузырей — синтезируется кодом при запуске игры.",
	"notes": "ЗАПИСКИ",
	"found": "НАЙДЕНО %d ИЗ %d",
	"close_note": "E — убрать",
	"close_journal": "J или Esc — закрыть",
	"order": "ПОРЯДОК:",
	# ПОМЕХИ НА ПОЛОТНЕ. Раньше их названия лежали в Shapes.MOD_NAME жёстко
	# по-русски, и в английском режиме игрок видел «НОМЕРКОВ НЕТ» посреди
	# английского интерфейса. Нашлось на кадре магазинного трейлера.
	"mod_no_nums": "НОМЕРКОВ НЕТ",
	"mod_lamp": "ПОЛОТНО В ТЕМНОТЕ",
	"mod_drift": "ТОЧКИ ПЛЫВУТ",
	"it_comes": "ОНО ИДЁТ",
	"fear": "СТРАХ x%.1f",
	"h_canvas": "ПОЛОТНО %d/%d",
	"h_findexit": "НАЙДИ ВЫХОД",
	"h_noexit": "ВЫХОДА НЕТ. ИДИ К ЖЁЛТОМУ СТОЛБУ.",
	"h_paused": "ПАУЗА — щёлкни по игре, чтобы продолжить",
	"h_thread_on": "НИТЬ ТЯНЕТСЯ.",
	"h_thread_off": "НИТЬ ОБОРВАНА.",
	"h_drawdoor": "НАРИСУЙ ДВЕРЬ",
	"h_left": "ОСТАВИЛ ПОЛОТНО.",
	"h_burst": "СТЕНА ЛОПНУЛА. ОНО ВЫШЛО.",
	"h_free": "ВЫРВАЛСЯ. ОНО УШЛО В КАМЕНЬ.",
	"h_dead": "ОНО ДОСТАЛО ТЕБЯ. R — ЕЩЁ РАЗ.",
	"h_nowand": "НЕЧЕМ. ПАЛОЧКА ОСТАЛАСЬ НА СТОЛЕ.",
	"h_noone": "РЯДОМ НИКОГО... ВСПЫШКУ ЛУЧШЕ БЕРЕЧЬ.",
	"h_charging": "ВСПЫШКА ЕЩЁ КОПИТСЯ. ОСТАЛОСЬ %d.",
	"h_canv_fled": "ПОЛОТНО УШЛО. ИЩИ ЕГО ЗАНОВО — НИТЬ ПОКАЖЕТ.",
	"m_torn": "Рисунок осыпался.",
	"m_miss": "Неверная точка.",
	"m_caught": "Оно тебя достало.",
	"m_nest": "Гнездо.",
	"g_wallburst": "ЩУПАЛЬЦА ИЗ СТЕНЫ! ЖМИ ПРОБЕЛ!",
	"g_nest": "ЩУПАЛЬЦА! ЖМИ ПРОБЕЛ!",
	"g_alive": "СТЕНА ЖИВАЯ! ЖМИ ПРОБЕЛ!",
	"win_text": "ТЫ ВЫБРАЛСЯ\n\nДверь ты нарисовал сам. Как и всё остальное здесь.\n\nR — ещё раз",
	"h_form": "ЭТО УЖЕ НЕ ОНО.",
	"h_climb": "ПРОЛОМ НАВЕРХУ. E — ПОДНЯТЬСЯ.",
	"p_look": "ЭТО НЕ ТВОЯ КОМНАТА. E — ЛАМПА.",
	"p_book": "У НЕЁ НА ОДЕЯЛЕ БЛОКНОТ. E — ВЗЯТЬ.",
	"p_draw": "СОЕДИНИ ТОЧКИ ПО ПОРЯДКУ.",
	"p_read": "СОЕДИНИ ТОЧКИ...",
	"p_hole": "ПОЛ ПРОВАЛИЛСЯ. ЛИАНЫ ВЕДУТ ТУДА.",
	"p_fall": "ПОЛ...",
	"h_hands": "РУКИ С ПОТОЛКА. ТЕБЯ ПОДНЯЛИ.",
	"h_tongue": "ЯЗЫК ИЗ ПАСТИ. ТЯНЕТ К СЕБЕ.",
	"h_slam": "ЩУПАЛЬЦЕ ШВЫРНУЛО ТЕБЯ В СТЕНУ.",
	"h_slam_up": "ПАЛОЧКА ВЫПАЛА. ОН ИДЁТ. ИЩИ ЕЁ.",
	"h_slam_pull": "ЩУПАЛЬЦЕ НА ТЕБЕ. ТЯНЕТ.",
	"h_slam_win": "ВСПЫШКА В УПОР. ОНО УШЛО В КАМЕНЬ.",
	"h_still": "ЗАМРИ. ОНИ ЩУПАЮТ ВОЗДУХ.",
	"h_still_ok": "НЕ ЗАМЕТИЛИ. ПРОШЛИ МИМО.",
	"h_flash": "ВСПЫШКА. ОНО ОТСТУПИЛО.",
	# ── ГОЛОС ТВАРИ. Слом четвёртой стены. Не заглавными, как подсказки: это
	# не служебная строка, а то, что с тобой заговорили. Условия и частота —
	# в ЧЕТВЁРТАЯ_СТЕНА.md, здесь только слова.
	"v_pause": "Пауза не работает. Я просто вежливый.",
	"v_waited": "Ты закрыл игру. Я подождал.",
	"v_days": "Тебя не было %d %s.",
	"v_focus": "Отвлёкся?",
	"v_night": "Три часа ночи. Конечно.",
	"v_long": "Сорок минут. И ты всё ещё думаешь, что выйдешь.",
	"v_count1": "Один раз. Я запомнил.",
	"v_count2": "Два раза. Я считаю.",
	"v_again": "Ты тут не первый раз.",
	"v_name": "Тебя ведь зовут не так.",
	"v_shake": "Ещё раз. У тебя дрожит рука.",
	"v_doors": "Ты думаешь, что рисуешь замки. Ты рисуешь двери.",
	"v_pretty": "Красиво. Это ничего не значит.",
	"v_who": "Кто научил тебя этим знакам?",
	"v_breath": "Я слышу, как ты дышишь. Не тем ртом.",
	"v_stop": "Ты можешь перестать в любой момент. Никто тебя не держит.",
	"v_chase": "Мне не нужно тебя догонять.",
	"v_door": "Эту дверь до тебя уже открывали.",
	"v_wrong": "Ты идёшь не туда. Но иди.",
	"v_dark": "Здесь темно не для тебя. Мне так удобнее.",
	"v_watch": "Я знаю, что это смотрит много людей.",
	"v_wave": "Помаши им.",
	"v_nohelp": "Они не помогут.",
	"v_f1": "Не закрывай. Досмотри.",
	"v_f2": "Ты держался дольше предыдущего.",
	"v_f3": "Тише. Это быстро.",
	"v_f4": "Смотри на руки. На меня не надо.",
	"v_f5": "Вот это я и хотел показать.",
	"v_f6": "Ты сам сюда шёл. Я даже не звал.",
	"d_one": "день",
	"d_few": "дня",
	"d_many": "дней",
	"h_crack": "КАМЕНЬ ТРЕЩИТ.",
	"h_eyes": "ИЗ КАМНЯ СМОТРЯТ.",
	"h_gone": "ОНО УШЛО В КАМЕНЬ. РУКИ НЕ СЛУШАЮТСЯ.",
	"h_angry": "ТЫ ЕГО РАЗОЗЛИЛ.",
	"quality": "КАЧЕСТВО",
	"q0": "НИЗКОЕ",
	"q1": "СРЕДНЕЕ",
	"q2": "ВЫСОКОЕ",
	"sens": "ЧУВСТВИТЕЛЬНОСТЬ МЫШИ",
	"gamma": "ЯРКОСТЬ",
	"q_restart": "ПЛОТНОСТЬ СЕТОК — ПОСЛЕ ПЕРЕЗАПУСКА",
	"d_title": "ОНО ДОСТАЛО ТЕБЯ",
	"d_sub": "двух раз хватило. лабиринт складывается заново, и всё сначала",
	"d_back": "ОБРАТНО В ЛАБИРИНТ",
	"d_key": "R — обратно в лабиринт",
	"g_mash": "ЖМИ ПРОБЕЛ! ВЫРЫВАЙСЯ!",
	"h_dumped": "ТЕБЯ БРОСИЛИ ЗДЕСЬ. ОН УЖЕ ИДЁТ.",
	"h_safe": "ТЁПЛЫЙ СВЕТ. СЮДА ОН НЕ ЗАЙДЁТ — НО НЕНАДОЛГО.",
	"g_shelter": "СТЕНА УБЕЖИЩА ТРЕСНУЛА! ЖМИ ПРОБЕЛ!",
	"g_wall": "СТЕНА ТРЕСНУЛА! ЖМИ ПРОБЕЛ!",
	"h_dropped": "ПАЛОЧКА ВЫПАЛА. G — НИТЬ ДОВЕДЁТ, E — ПОДНЯТЬ.",
	"h_picked": "ПАЛОЧКА СНОВА В РУКЕ.",
	"viewer": "СМОТРОВАЯ",
	"lang_name": "ЯЗЫК:  РУССКИЙ  ▸  ENGLISH",
}

const EN := {
	"title": "DOTS OF TERROR",
	"sub": "first-person horror  ·  play with headphones",
	"intro1": "You wake in complete darkness.",
	"intro2": "TURN AROUND — there is a wand on the table behind you. No light without it.",
	"intro3": "Find seven canvases, connect the dots, and reach the way out.",
	"k_move": "walk",
	"k_look": "look,  SHIFT — faster",
	"k_dash": "dash,  and break free when grabbed",
	"k_flash": "wand flash",
	"k_read": "read a book, or drop the canvas",
	"k_journal": "notes journal",
	"k_thread": "thread: where to go next",
	"k_turn": "turn around",
	"k_pause": "pause",
	"k_restart": "start over",
	"k_mouse": "mouse  or  ← →",
	"music": "MUSIC",
	"sounds": "SOUNDS",
	"controls": "CONTROLS",
	"bind_hint": "press a key  •  ESC — cancel",
	"bind_reset": "RESTORE DEFAULTS",
	"bind_back": "BACK",
	"bind_pad": "gamepad: left stick — walk, right — look, A — dash,\nX — flash, Y — take, LB — faster, RB — turn around,\nSTART — pause, SELECT — journal, d-pad up — thread",
	"b_forward": "forward",
	"b_back": "back",
	"b_left": "left",
	"b_right": "right",
	"b_run": "faster",
	"b_sprint": "dash / break free",
	"b_quick_turn": "turn around",
	"b_flash": "flash",
	"b_read": "take / drop",
	"b_journal": "journal",
	"b_thread": "thread",
	"k_space": "SPACE",
	"r1": "Connect the dots in colour order — the ribbon below the canvas.",
	"r2": "Colours repeat: check the small numbers beside the dots.",
	"r3": "Every dot you connect eats two seconds off the timer.",
	"r4": "Every mistake and every capture makes the maze worse.",
	"r5": "IT DOES NOT WAIT while you draw. It will tear the canvas away.",
	"r6": "When the canvas hum goes quiet, it is close. Drop it and run.",
	"r7": "Hear stone cracking behind you — TURN AROUND.",
	"r8": "What you look at does not grab you.",
	"r9": "Three captures in a row and everything starts again.",
	"wake": "WAKE UP",
	"quit": "QUIT",
	"credits": "CREDITS",
	"volume": "VOLUME",
	"paused": "PAUSED",
	"resume": "RESUME",
	"restart": "START OVER",
	"wipe": "ERASE JOURNAL",
	"wipe_sure": "ERASE FOR SURE?",
	"wipe_done": "JOURNAL EMPTY",
	"quit_game": "QUIT GAME",
	"esc_back": "ESC — back",
	"back": "BACK",
	"cred_intro": "Sounds taken from opengameart.org. Authors and licences below.",
	"cred_cc0": "CC0 — public domain, no attribution required.",
	"cred_by": "BY — attribution required. It is given above.",
	"cred_rest1": "Everything else — the monster's steps, tentacles, canvas hum,",
	"cred_rest2": "drips, bubble pops — is synthesised in code at startup.",
	"notes": "NOTES",
	"found": "FOUND %d OF %d",
	"close_note": "E — put away",
	"close_journal": "J or Esc — close",
	"order": "ORDER:",
	"mod_no_nums": "NO NUMBERS",
	"mod_lamp": "CANVAS IN THE DARK",
	"mod_drift": "THE DOTS DRIFT",
	"it_comes": "IT IS COMING",
	"fear": "FEAR x%.1f",
	"h_canvas": "CANVAS %d/%d",
	"h_findexit": "FIND THE WAY OUT",
	"h_noexit": "THERE IS NO EXIT. GO TO THE YELLOW FRAME.",
	"h_paused": "PAUSED — click the game to resume",
	"h_thread_on": "THE THREAD REACHES OUT.",
	"h_thread_off": "THE THREAD IS CUT.",
	"h_drawdoor": "DRAW THE DOOR",
	"h_left": "YOU LEFT THE CANVAS.",
	"h_burst": "THE WALL BURST. IT IS OUT.",
	"h_free": "YOU BROKE FREE. IT WENT BACK INTO STONE.",
	"h_dead": "IT GOT YOU. R — TRY AGAIN.",
	"h_nowand": "NOTHING TO USE. THE WAND IS ON THE TABLE.",
	"h_noone": "NOBODY NEAR... SAVE THE FLASH.",
	"h_charging": "THE FLASH IS STILL CHARGING. %d LEFT.",
	"h_canv_fled": "THE CANVAS LEFT. FIND IT AGAIN — THE THREAD WILL SHOW.",
	"m_torn": "The drawing crumbled.",
	"m_miss": "Wrong dot.",
	"m_caught": "It got to you.",
	"m_nest": "A nest.",
	"g_wallburst": "TENTACLES FROM THE WALL! HIT SPACE!",
	"g_nest": "TENTACLES! HIT SPACE!",
	"g_alive": "THE WALL IS ALIVE! HIT SPACE!",
	"win_text": "YOU GOT OUT\n\nYou drew that door yourself. Like everything else here.\n\nR to go again",
	"h_form": "THAT IS NOT IT ANYMORE.",
	"h_climb": "A HOLE ABOVE. E TO CLIMB.",
	"p_look": "THIS IS NOT YOUR ROOM. E FOR THE LAMP.",
	"p_book": "A NOTEBOOK ON HER BLANKET. E TO TAKE IT.",
	"p_draw": "CONNECT THE DOTS IN ORDER.",
	"p_read": "CONNECT THE DOTS...",
	"p_hole": "THE FLOOR GAVE WAY. THE VINES LEAD THERE.",
	"p_fall": "THE FLOOR...",
	"h_hands": "HANDS FROM THE CEILING. YOU ARE OFF THE FLOOR.",
	"h_tongue": "A TONGUE FROM THE MAW. IT PULLS.",
	"h_slam": "A TENTACLE THREW YOU INTO THE WALL.",
	"h_slam_up": "THE WAND IS GONE. HE IS COMING. FIND IT.",
	"h_slam_pull": "A TENTACLE HAS YOU. IT PULLS.",
	"h_slam_win": "A FLASH POINT-BLANK. IT WENT BACK INTO THE STONE.",
	"h_still": "FREEZE. THEY ARE FEELING THE AIR.",
	"h_still_ok": "THEY DID NOT NOTICE. THEY PASSED.",
	"h_flash": "FLASH. IT PULLED BACK.",
	"v_pause": "Pause does not work. I am simply being polite.",
	"v_waited": "You closed the game. I waited.",
	"v_days": "You were gone %d %s.",
	"v_focus": "Distracted?",
	"v_night": "Three in the morning. Of course.",
	"v_long": "Forty minutes. And you still think you will get out.",
	"v_count1": "Once. I remembered.",
	"v_count2": "Twice. I am counting.",
	"v_again": "You have been here before.",
	"v_name": "That is not really your name.",
	"v_shake": "Again. Your hand is shaking.",
	"v_doors": "You think you are drawing locks. You are drawing doors.",
	"v_pretty": "Pretty. It means nothing.",
	"v_who": "Who taught you these signs?",
	"v_breath": "I hear you breathing. Not through that mouth.",
	"v_stop": "You can stop at any moment. Nobody is holding you.",
	"v_chase": "I do not need to catch up with you.",
	"v_door": "This door was opened before you.",
	"v_wrong": "You are going the wrong way. But go.",
	"v_dark": "It is not dark for you. It is just easier for me.",
	"v_watch": "I know a lot of people are watching this.",
	"v_wave": "Wave to them.",
	"v_nohelp": "They will not help.",
	"v_f1": "Do not close it. Watch to the end.",
	"v_f2": "You lasted longer than the last one.",
	"v_f3": "Quiet. This is quick.",
	"v_f4": "Look at the hands. Not at me.",
	"v_f5": "This is what I wanted to show you.",
	"v_f6": "You walked here yourself. I did not even call.",
	"d_one": "day",
	"d_few": "days",
	"d_many": "days",
	"h_crack": "THE STONE IS CRACKING.",
	"h_eyes": "SOMETHING WATCHES FROM THE STONE.",
	"h_gone": "IT WENT INTO STONE. YOUR HANDS WILL NOT OBEY.",
	"h_angry": "YOU HAVE ANGERED IT.",
	"quality": "QUALITY",
	"q0": "LOW",
	"q1": "MEDIUM",
	"q2": "HIGH",
	"sens": "MOUSE SENSITIVITY",
	"gamma": "BRIGHTNESS",
	"q_restart": "MESH DENSITY APPLIES AFTER RESTART",
	"d_title": "IT GOT YOU",
	"d_sub": "twice was enough. the maze re-forms, and it all starts over",
	"d_back": "BACK INTO THE MAZE",
	"d_key": "R — back into the maze",
	"g_mash": "MASH SPACE! BREAK FREE!",
	"h_dumped": "YOU WERE LEFT HERE. HE IS ALREADY COMING.",
	"h_safe": "WARM LIGHT. HE WILL NOT COME IN — BUT NOT FOR LONG.",
	"g_shelter": "THE SHELTER WALL CRACKED! MASH SPACE!",
	"g_wall": "THE WALL CRACKED! MASH SPACE!",
	"h_dropped": "THE WAND FELL. G FOR THE THREAD, E TO PICK IT UP.",
	"h_picked": "THE WAND IS IN YOUR HAND AGAIN.",
	"viewer": "VIEWING ROOM",
	"lang_name": "LANGUAGE:  ENGLISH  ▸  РУССКИЙ",
}

## Ключа нет ни в одном словаре — возвращаем сам ключ. Пропущенная строка должна
## бросаться в глаза на экране, а не падать игрой у игрока.
static func t(key: String) -> String:
	var d: Dictionary = EN if Settings.lang == "en" else RU
	if d.has(key):
		return str(d[key])
	if RU.has(key):
		return str(RU[key])
	return "[" + key + "]"


static func toggle() -> void:
	Settings.set_lang("en" if Settings.lang == "ru" else "ru")


## СКЛОНЕНИЕ ДНЕЙ. «Тебя не было 2 дней» ломает самую страшную фразу в наборе
## быстрее, чем что угодно другое: игрок замечает ошибку и вспоминает, что перед
## ним программа. По-английски правило проще, но ветка одна на оба языка.
static func days(n: int) -> String:
	var a: int = n % 100
	if a >= 11 and a <= 14:
		return t("d_many")
	match n % 10:
		1:
			return t("d_one")
		2, 3, 4:
			return t("d_few")
	return t("d_many")
